$bloatware = @(
    "*Microsoft.3dbuilder*"
    "*AdobeSystemsIncorporated.AdobePhotoshopExpress*"
    "*ThumbmunkeysLtd.PhototasticCollage*"
    "*Microsoft.WindowsAlarms*"
    "*Microsoft.Asphalt8Airborne*"
    "*microsoft.windowscommunicationsapps*"
    "*Microsoft.WindowsCamera*"
    "*NORDCURRENT.COOKINGFEVER*"
    "*Fitbit.FitbitCoach*"
    "*king.com.CandyCrushSodaSaga*"
    "*Microsoft.DrawboardPDF*"
    "*Facebook*"
    "*BethesdaSoftworks.FalloutShelter*"
    "*FarmVille2CountryEscape*"
    "*Microsoft.WindowsFeedbackHub*"
    "*Microsoft.GetHelp*"
    "*Microsoft.Getstarted*"
    "*Microsoft.ZuneMusic*"
    "*Microsoft.WindowsMaps*"
    "*Microsoft.Messaging"
    "*Microsoft.Wallet*"
    "*Microsoft.MicrosoftSolitaireCollection*"
    "*Microsoft.YourPhone*"
    "*Todos*"
    "*ConnectivityStore*"
    "*MinecraftUWP*"
    "*Microsoft.OneConnect*"
    "*Microsoft.BingFinance*"
    "*Microsoft.ZuneVideo*"
    "*Microsoft.BingNews*"
    "*Microsoft.MicrosoftOfficeHub*"
    "*Netflix*"
    "*OneNote*"
    "*Microsoft.MSPaint*"
    "*PandoraMediaInc*"
    "*Microsoft.People*"
    "*CommsPhone*"
    "*windowsphone*"
    "*Microsoft.Print3D*"
    "*flaregamesGmbH.RoyalRevolt2*"
    "*WindowsScan*"
    "*AutodeskSketchBook*"
    "*Microsoft.SkypeApp*"
    "*bingsports*"
    "*Office.Sway*"
    "*Microsoft.Getstarted*"
    "*Microsoft3DViewer*"
    "*Microsoft.WindowsSoundRecorder*"
    "*Microsoft.BingWeather*"
    "*Microsoft.MicrosoftStickyNotes*"
    "*Microsoft.MixedReality.Portal*"
    "*Microsoft.XboxApp*"
    "*XboxOneSmartGlass*"
    "*Microsoft.XboxSpeechToTextOverlay*"
    "*Microsoft.XboxIdentityProvider*"
    "*Microsoft.XboxGameOverlay*"
    "*Microsoft.XboxGamingOverlay*"
    "*Microsoft.ZuneMusic*"
)

Write-Output "Uninstalling Bloatware..."

foreach ($appName in $bloatware) {
    Write-Output "Uninstalling $appName..."
    Get-AppxPackage -Name $appName | Remove-AppxPackage -ErrorAction SilentlyContinue
}
